reporting:
  watermarks:
    statements: [50, 80]
    lines: [50, 80]
    functions: [50, 80]
    branches: [50, 80]
  dir: build/test/coverage/web
  reports:
    - text-summary
    - lcovonly
    - cobertura
    - html
  report-config:
    cobertura:
      file: js_coverage.xml
    lcovonly:
      file: lcov.info
